### ISSUE TITLE
Sparse POA isn't actually sparse, uses too much memory

### ISSUE THREAD

**Issue by nlhepler** [PacificBiosciences/ConsensusCore2#16]

**Comment by nlhepler** [comment]
https://github.com/PacificBiosciences/ConsensusCore2/blob/master/src/poa/PoaGraphImpl.cpp#L142

**Comment by dalexander** [comment]
I am ready to look at this now

**Comment by dalexander** [comment]
I've changed the title to reflect the overarching problem

**Comment by evolvedmicrobe** [comment]
@dalexander @nlhepler Liz has a few examples of long IsoSeq transcripts that start consuming many gigabytes of memory, hit the swap and just hangs (this is with the --noPolish POA only option).  Apparently this did not happen on the old CCS, so I assume is due to this POA issue.  Should we start engineering a work around for these cases, or do you think we can solve this fast enough?

**Comment by dalexander** [comment]
I have the fix basically in-hand at this point, I'd love to try it out on Liz's dataset

**Comment by dalexander** [comment]
fixed now, merged into master
